### ISSUE TITLE
Mailer :: Feature request

### ISSUE THREAD

**Issue by ghost** [thewebchameleon/Template.MVC#1]
Hi @thewebchameleon ,

Reset password and Register/create account requires a mailer to send out activation and reset password links.

Example configuration
```
"Smtp": {
    "Host": "host name",
    "Username": "mail-donotreply@example.com",
    "Password": "password",
    "Ssl": true,
    "Port": 587,
    "From": "mail-donotreply@example.com"
}
```

Check out this library https://github.com/jstedfast/MailKit

**Comment by thewebchameleon** [comment]
Hi @nicotravassos 

I have added email functionality and forgot password in [this commit](https://github.com/thewebchameleon/Template.MVC/commit/2ea8c848a10e9ca4049836fa43931a9e47aa046e)

**Comment by ghost** [comment]
Thank you @thewebchameleon
