### ISSUE TITLE
AspNetCore 2.2 :: Capability

### ISSUE THREAD

**Issue by ghost** [thewebchameleon/Template.MVC#2]
Hi @thewebchameleon,

Is this template compatible with aspnetcore 2.2 if not do have a version of this template which is using aspnetcore 2.2?

**Comment by thewebchameleon** [comment]
Hi @nicotravassos 

I have created a [branch](https://github.com/thewebchameleon/Template.MVC/tree/aspcore-2) and converted the template to aspnet core 2.2

[This commit](https://github.com/thewebchameleon/Template.MVC/commit/d3050fa33f8bdff6629b0051f4b49d9e1cc31d80) details the changes I had to make

**Comment by ghost** [comment]
Thank you @thewebchameleon

**Comment by ghost** [comment]
Hi @thewebchameleon,

Was this branch deleted?

**Comment by thewebchameleon** [comment]
@nicotravassos yes, this was accidental. 

If you would like, i can recreate it for you?

**Comment by ghost** [comment]
Yes please @thewebchameleon

**Comment by thewebchameleon** [comment]
hi @nicotravassos 

I have created a fresh branch from master - [aspcore-2](https://github.com/thewebchameleon/Template.MVC/tree/aspcore-2)
