### ISSUE TITLE
MySQL :: Feature request

### ISSUE THREAD

**Issue by ghost** [thewebchameleon/Template.MVC#3]
Hi @thewebchameleon,

Requesting feature MySQL as database option.

```
"ConnectionStrings": {
    "DefaultConnection": ""
},
"NetCoreTemplate": {
    "DatabaseProvider": "MySQL"
}
```

**Comment by ghost** [comment]
@thewebchameleon I would really appreciate this feature.

**Comment by thewebchameleon** [comment]
added, see [this commit](https://github.com/thewebchameleon/Template.MVC/commit/0f7891744ae87809190e5dca8af681f947808b12)

note: the deployment script and database project will not be compatible with MySQL

**Comment by ghost** [comment]
@thewebchameleon Thank you for this.

Question
```
"ConnectionStrings": {
    "DefaultConnection": "Server=.;Database=template;Trusted_Connection=True;",
    "Timeout": 5000
  },
```

Should this connection string above work fine or am I missing something?

Should I add 

```
"DatabaseProvider": "MySQL"
```
within config?

**Comment by thewebchameleon** [comment]
it would look something like this

```
"ConnectionStrings": {
    "DefaultConnection": "server=localhost;uid=root;pwd=somepassword;database=template;",
    "Timeout": 5000
  },
```

**Comment by ghost** [comment]
Thank you @thewebchameleon.
