### ISSUE TITLE
Template :: Theme

### ISSUE THREAD

**Issue by ghost** [thewebchameleon/Template.MVC#7]
Hi @thewebchameleon,

I have been considering building a simple bootstrap template for this project.
Something exciting like this [example](http://demo.adminbootstrap.com/elements/1.3.0/demo/) but this example is poorly built.

If you approve of my design will you consider using it on this template or even keeping the pull request open as a **_STICKY_**?

**Comment by thewebchameleon** [comment]
I think this is great idea, i am open to any contributions. 

Besides the example mentioned above, what are your thoughts on deciding the design style? I've been considering [materializecss](https://materializecss.com/)

**Comment by ghost** [comment]
I was considering clean and simple **bootstrap** 4.3.1. Just the looks are going to be more refined and exciting. The **Materialize** idea is great but who ever uses this template is just going to replace it I guess. Since we using **bootstrap** why not just tweak and let the end user worrying about making it beautiful.

When I am done with my theme and you do not fancy it you can always keep it as a **STICKY PULL REQUEST** 😄.

**Comment by thewebchameleon** [comment]
I agree with keeping it simple with bootstrap, go for it.

**Comment by thewebchameleon** [comment]
[TemplateV2.Razor](https://github.com/thewebchameleon/TemplateV2.Razor) is next iteration of this project and uses the [SB-Admin2](https://startbootstrap.com/themes/sb-admin-2/) theme with bootstrap.
